version: 2

sources:
  - name: SAMPLE_DB1_SCHEMA
    schema: SAMPLE_DB1_SCHEMA
    database: SAMPLE_DB1
    tables:
      - name: CUSTOMER
        identifier: CUSTOMER
      - name: PRODUCT
        identifier: PRODUCT
